create table if not exists public.whitelist_registrations (
  id bigint generated by default as identity primary key,
  submitted_at timestamptz not null default now(),
  username text not null check (char_length(username) between 1 and 100),
  wallet_address text not null check (char_length(wallet_address) between 1 and 200),
  tasks_completed text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.whitelist_registrations enable row level security;

drop policy if exists "Anyone can submit a whitelist registration"
  on public.whitelist_registrations;

create policy "Anyone can submit a whitelist registration"
  on public.whitelist_registrations
  for insert
  to anon
  with check (
    char_length(username) between 1 and 100
    and char_length(wallet_address) between 1 and 200
  );

do $$
begin
  alter publication supabase_realtime
    add table public.whitelist_registrations;
exception
  when duplicate_object then null;
end
$$;